trigger:
  branches:
    include:
      - main  https://github.com/ProjectBlackSpider/Flask.git

jobs:
- job: Build
  displayName: 'Build and Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task:AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: ''
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login'
  - script: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      #pytest
    displayName: 'Build, Install Dependencies, and Run Tests'

- job: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      az login
      az webapp up --name app.py --resource-group test --plan flask --location west-region
    displayName: 'Deploy to Azure Web App'
